"""estructura_inicial

Revision ID: 36a3c839603b
Revises: 
Create Date: 2026-06-08 07:21:13.485860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36a3c839603b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('componentes_evaluacion')
    op.drop_table('competencias_periodo')
    op.drop_table('examen_contenido')
    with op.batch_alter_table('ingresos_colegio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unico_evento_por_dia'))

    op.drop_table('ingresos_colegio')
    op.drop_table('modelo_evaluacion_estudiante')
    op.drop_table('configuracion_evaluacion')
    with op.batch_alter_table('acudientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_acudientes_colegio'))

    with op.batch_alter_table('acuerdos_correctivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compromisos', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('cumplido', sa.Boolean(), nullable=True))
        batch_op.drop_column('compromiso')
        batch_op.drop_column('estado')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('acuerdos_evaluacion', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BORRADOR', 'CERRADO', name='estado_acuerdo'),
               nullable=False,
               existing_server_default=sa.text("'BORRADOR'::character varying"))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('unico_docente_anio'), type_='unique')
        batch_op.create_unique_constraint('unique_docente_anio', ['docente_id', 'anio'])
        batch_op.drop_constraint(batch_op.f('fk_acuerdo_colegio'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_acuerdo_docente'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'])
        batch_op.create_foreign_key(None, 'docentes', ['docente_id'], ['id'])

    with op.batch_alter_table('ajustes_razonables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.alter_column('aplicado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('fecha_aplicacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activa', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('unica_alerta_activa'), postgresql_where='(atendida = false)')
        batch_op.drop_column('atendida')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('areas_gestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.drop_constraint(batch_op.f('fk_area_colegio'), type_='foreignkey')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('porcentaje')
        batch_op.drop_column('colegio_id')
        batch_op.drop_column('activo')

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.alter_column('clase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unica_asistencia_por_clase'), type_='unique')

    with op.batch_alter_table('citaciones_acudiente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_citaciones_estado_pendiente'), postgresql_where="((estado)::text = 'pendiente'::text)")
        batch_op.drop_index(batch_op.f('idx_citaciones_estudiante_acudiente'))
        batch_op.drop_index(batch_op.f('unique_citacion_por_novedad'), postgresql_where='(tipo_origen IS NOT NULL)')
        batch_op.drop_index(batch_op.f('unique_citacion_por_tipo'), postgresql_where='(tipo_origen IS NOT NULL)')
        batch_op.drop_column('tipo_origen')
        batch_op.drop_column('fecha')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('clase_estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unica_matricula'), type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.alter_column('dia',
               existing_type=postgresql.ENUM('lunes', 'martes', 'miercoles', 'jueves', 'viernes', name='dia_semana'),
               type_=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', name='diasemana'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('horario_unico'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_clase_grupo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'])
        batch_op.drop_column('grupo_id')

    with op.batch_alter_table('competencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unica_competencia_por_area'), type_='unique')
        batch_op.drop_constraint(batch_op.f('unico_orden_por_area'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_competencia_area'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('area_id')
        batch_op.drop_column('orden')
        batch_op.drop_column('activo')

    with op.batch_alter_table('competencias_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('porcentaje',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('competencias_materia_materia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contribuciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criterio_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unico_orden_por_competencia'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_contribucion_competencia'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'criterios_evaluacion', ['criterio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('competencia_id')
        batch_op.drop_column('orden')
        batch_op.drop_column('activo')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coordinador_sede'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_coordinador_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sedes', ['sede_id', 'colegio_id'], ['id', 'colegio_id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('criterios_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_gestion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('porcentaje', sa.Float(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_criterio_acuerdo'))
        batch_op.drop_constraint(batch_op.f('fk_criterio_contribucion'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_criterio_acuerdo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'areas_gestion', ['area_gestion_id'], ['id'])
        batch_op.create_foreign_key(None, 'acuerdos_evaluacion', ['acuerdo_id'], ['id'])
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('contribucion_id')

    with op.batch_alter_table('descargos_estudiante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['novedad_id'])

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_docente_sede_colegio'), type_='foreignkey')

    with op.batch_alter_table('escala_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_minima', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('nota_maxima', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('colegio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_escala_colegio'))
        batch_op.drop_column('tipo_escala')
        batch_op.drop_column('nota_max')
        batch_op.drop_column('nota_min')

    with op.batch_alter_table('estudiante_acudiente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unica_relacion'), type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_estudiante_grupo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_estudiante_sede_colegio'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_estudiante_jornada'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'jornadas_colegio', ['jornada_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'grupos', ['grupo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('evaluacion_criterio', schema=None) as batch_op:
        batch_op.alter_column('calificacion',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_evalcriterio_evalfinal'))
        batch_op.drop_constraint(batch_op.f('unica_eval_por_criterio'), type_='unique')
        batch_op.create_unique_constraint('unique_evaluacion_criterio', ['evaluacion_final_id', 'criterio_id'])
        batch_op.drop_constraint(batch_op.f('fk_evalcriterio_criterio'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_evalcriterio_evalfinal'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'criterios_evaluacion', ['criterio_id'], ['id'])
        batch_op.create_foreign_key(None, 'evaluacion_final', ['evaluacion_final_id'], ['id'])

    with op.batch_alter_table('evaluacion_final', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('puntaje_final', sa.Float(), nullable=True))
        batch_op.alter_column('fecha_cierre',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('fk_eval_acuerdo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'acuerdos_evaluacion', ['acuerdo_id'], ['id'])
        batch_op.drop_column('observaciones_finales')
        batch_op.drop_column('estado')

    with op.batch_alter_table('evaluaciones_estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=False))
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('indicador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('periodo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_estudiante_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_periodo_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estudiantes', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'periodos', ['periodo_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('calificacion')

    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_subida', sa.DateTime(), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('fk_evidencia_criterio'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'criterios_evaluacion', ['criterio_id'], ['id'])
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('observacion_admin')

    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('colegio_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_examenes_contenido_json'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_examenes_tipo_examen_id'))
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tiempo_limite_minutos')
        batch_op.drop_column('titulo')
        batch_op.drop_column('activo')

    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.alter_column('grado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('grupo_unico'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_grupo_jornada'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_grupo_director'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_grupo_sede'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_grupo_colegio'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'docentes', ['director_docente_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'jornadas_colegio', ['jornada_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('indicadores_logro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia_id', sa.Integer(), nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_indicador_competencia_materia'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencias_materia', ['competencia_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('competencia_materia_id')

    with op.batch_alter_table('jornadas_colegio', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_jornada_colegio'), type_='unique')
        batch_op.drop_index(batch_op.f('unique_jornada_colegio_lower'))
        batch_op.drop_constraint(batch_op.f('unique_jornada_nombre_por_colegio'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_jornada_sede'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('justificaciones_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('justificacion')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_notification_logs_estado_tipo'), postgresql_where="((estado)::text <> 'enviado'::text)")
        batch_op.create_index(batch_op.f('ix_notification_logs_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.alter_column('tipo_novedad',
               existing_type=postgresql.ENUM('DISCIPLINA', 'ACADEMICO', 'LLEGADA_TARDE', name='tipo_novedad_enum'),
               type_=sa.Enum('DISCIPLINA', 'ACADEMICO', 'LLEGADA_TARDE', name='tiponovedad'),
               existing_nullable=False)
        batch_op.alter_column('gravedad',
               existing_type=postgresql.ENUM('Tipo 1', 'Tipo 2', 'Tipo 3', name='tipo_gravedad'),
               type_=sa.Enum('TIPO_1', 'TIPO_2', 'TIPO_3', name='tipogravedad'),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'usuarios', ['registrada_por'], ['id'])

    with op.batch_alter_table('periodos_academicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anio', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('periodos_academicos_colegio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('orden')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('es_final')

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('piar', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('unico_piar_activo'), postgresql_where='(activo = true)')

    with op.batch_alter_table('respuestas_examen_detalle', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'resultados_examen', ['resultado_examen_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('respuestas_novedad', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('fk_respuesta_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('rol')

    with op.batch_alter_table('resultados_examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Enum('BAJO', 'BASICO', 'ALTO', 'SUPERIOR', name='niveldesempeno'), nullable=True))
        batch_op.add_column(sa.Column('cuestionario_archivo', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('resultado_unico_estudiante_examen'), type_='unique')
        batch_op.drop_column('total_preguntas')

    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sede_colegio_unico'), type_='unique')

    with op.batch_alter_table('seguimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('recomendaciones')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('activa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('fecha_fin',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('unico_colegio_suscripcion'), type_='unique')
        batch_op.drop_column('en_prueba')
        batch_op.drop_column('activo')
        batch_op.drop_column('limite_sedes')
        batch_op.drop_column('precio_base')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuario_sede_colegio'), type_='foreignkey')
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuario_sede_colegio'), 'sedes', ['sede_id', 'colegio_id'], ['id', 'colegio_id'])

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_base', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('limite_sedes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('en_prueba', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('unico_colegio_suscripcion'), ['colegio_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('activa')
        batch_op.drop_column('plan')

    with op.batch_alter_table('seguimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recomendaciones', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('observacion')

    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('sede_colegio_unico'), ['id', 'colegio_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('resultados_examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_preguntas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('resultado_unico_estudiante_examen'), ['estudiante_id', 'examen_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('cuestionario_archivo')
        batch_op.drop_column('nivel')

    with op.batch_alter_table('respuestas_novedad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', postgresql.ENUM('superadmin', 'admin_colegio', 'docente', 'estudiante', 'acudiente', 'coordinador', name='rol_usuario'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_respuesta_usuario'), 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('respuestas_examen_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('piar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unico_piar_activo'), ['estudiante_id'], unique=True, postgresql_where='(activo = true)')
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True, comment='Indica si el permiso académico está vigente. No controla acceso al sistema.'))

    with op.batch_alter_table('periodos_academicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('periodos_academicos_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'])
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('anio')

    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('gravedad',
               existing_type=sa.Enum('TIPO_1', 'TIPO_2', 'TIPO_3', name='tipogravedad'),
               type_=postgresql.ENUM('Tipo 1', 'Tipo 2', 'Tipo 3', name='tipo_gravedad'),
               existing_nullable=False)
        batch_op.alter_column('tipo_novedad',
               existing_type=sa.Enum('DISCIPLINA', 'ACADEMICO', 'LLEGADA_TARDE', name='tiponovedad'),
               type_=postgresql.ENUM('DISCIPLINA', 'ACADEMICO', 'LLEGADA_TARDE', name='tipo_novedad_enum'),
               existing_nullable=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_tipo'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_estado'))
        batch_op.create_index(batch_op.f('idx_notification_logs_estado_tipo'), ['estado', 'tipo'], unique=False, postgresql_where="((estado)::text <> 'enviado'::text)")
        batch_op.alter_column('payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('justificaciones_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificacion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('jornadas_colegio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jornada_sede'), 'sedes', ['sede_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('unique_jornada_nombre_por_colegio'), ['colegio_id', 'nombre'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('unique_jornada_colegio_lower'), ['colegio_id', sa.literal_column('lower(nombre::text)')], unique=True)
        batch_op.create_unique_constraint(batch_op.f('unique_jornada_colegio'), ['colegio_id', 'id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('indicadores_logro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia_materia_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_indicador_competencia_materia'), 'competencias_materia', ['competencia_materia_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('competencia_id')

    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_grupo_colegio'), 'colegios', ['colegio_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_grupo_sede'), 'sedes', ['sede_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_grupo_director'), 'docentes', ['director_docente_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_grupo_jornada'), 'jornadas_colegio', ['jornada_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('grupo_unico'), ['colegio_id', 'sede_id', 'jornada_id', 'anio_lectivo', 'grado', 'nombre'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('grado',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tiempo_limite_minutos', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_examenes_tipo_examen_id'), ['tipo_examen_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_examenes_contenido_json'), ['contenido_json'], unique=False, postgresql_using='gin')
        batch_op.drop_column('colegio_id')
        batch_op.drop_column('materia_id')
        batch_op.drop_column('fecha')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion_admin', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evidencia_criterio'), 'criterios_evaluacion', ['criterio_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('fecha_subida')

    with op.batch_alter_table('evaluaciones_estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_periodo_id_fkey'), 'periodos_academicos', ['periodo_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_estudiante_id_fkey'), 'estudiantes', ['estudiante_id'], ['id'])
        batch_op.alter_column('periodo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('indicador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('nota')

    with op.batch_alter_table('evaluacion_final', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'ABIERTO'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observaciones_finales', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_eval_acuerdo'), 'acuerdos_evaluacion', ['acuerdo_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('fecha_cierre',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('puntaje_final')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('evaluacion_criterio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evalcriterio_evalfinal'), 'evaluacion_final', ['evaluacion_final_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_evalcriterio_criterio'), 'criterios_evaluacion', ['criterio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_evaluacion_criterio', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unica_eval_por_criterio'), ['evaluacion_final_id', 'criterio_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_evalcriterio_evalfinal'), ['evaluacion_final_id'], unique=False)
        batch_op.alter_column('calificacion',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_estudiante_jornada'), 'jornadas_colegio', ['colegio_id', 'jornada_id'], ['colegio_id', 'id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_estudiante_sede_colegio'), 'sedes', ['sede_id', 'colegio_id'], ['id', 'colegio_id'])
        batch_op.create_foreign_key(batch_op.f('fk_estudiante_grupo'), 'grupos', ['grupo_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('estudiante_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unica_relacion'), ['estudiante_id', 'acudiente_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('escala_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_min', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nota_max', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_escala', sa.VARCHAR(length=20), server_default=sa.text("'NUMERICA'::character varying"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_escala_colegio'), ['colegio_id'], unique=False)
        batch_op.alter_column('colegio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nota_maxima')
        batch_op.drop_column('nota_minima')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_docente_sede_colegio'), 'sedes', ['sede_id', 'colegio_id'], ['id', 'colegio_id'])

    with op.batch_alter_table('descargos_estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('criterios_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribucion_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_criterio_acuerdo'), 'acuerdos_evaluacion', ['acuerdo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_criterio_contribucion'), 'contribuciones', ['contribucion_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_criterio_acuerdo'), ['acuerdo_id'], unique=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('porcentaje')
        batch_op.drop_column('nombre')
        batch_op.drop_column('area_gestion_id')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_coordinador_usuario'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_coordinador_sede'), 'sedes', ['sede_id'], ['id'])

    with op.batch_alter_table('contribuciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('competencia_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_contribucion_competencia'), 'competencias', ['competencia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unico_orden_por_competencia'), ['competencia_id', 'orden'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('criterio_id')

    with op.batch_alter_table('competencias_materia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('competencias_materia_materia_id_fkey'), 'materias', ['materia_id'], ['id'])
        batch_op.alter_column('porcentaje',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('competencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_competencia_area'), 'areas_gestion', ['area_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unico_orden_por_area'), ['area_id', 'orden'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('unica_competencia_por_area'), ['area_id', 'nombre'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('materia_id')
        batch_op.drop_column('porcentaje')

    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_clase_grupo'), 'grupos', ['grupo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('horario_unico'), ['docente_id', 'dia', 'hora_inicio', 'hora_fin'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('dia',
               existing_type=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', name='diasemana'),
               type_=postgresql.ENUM('lunes', 'martes', 'miercoles', 'jueves', 'viernes', name='dia_semana'),
               existing_nullable=False)

    with op.batch_alter_table('clase_estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unica_matricula'), ['clase_id', 'estudiante_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('citaciones_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_origen', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('unique_citacion_por_tipo'), ['estudiante_id', 'tipo_origen'], unique=True, postgresql_where='(tipo_origen IS NOT NULL)')
        batch_op.create_index(batch_op.f('unique_citacion_por_novedad'), ['novedad_id', 'tipo_origen'], unique=True, postgresql_where='(tipo_origen IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_citaciones_estudiante_acudiente'), ['estudiante_id', 'acudiente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_citaciones_estado_pendiente'), ['estado'], unique=False, postgresql_where="((estado)::text = 'pendiente'::text)")

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unica_asistencia_por_clase'), ['estudiante_id', 'clase_id', 'fecha'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('clase_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('areas_gestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_area_colegio'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atendida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('unica_alerta_activa'), ['estudiante_id', 'tipo'], unique=True, postgresql_where='(atendida = false)')
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('activa')

    with op.batch_alter_table('ajustes_razonables', schema=None) as batch_op:
        batch_op.alter_column('fecha_aplicacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('aplicado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('acuerdos_evaluacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_acuerdo_docente'), 'docentes', ['docente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_acuerdo_colegio'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_docente_anio', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unico_docente_anio'), ['docente_id', 'anio'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('estado',
               existing_type=sa.Enum('BORRADOR', 'CERRADO', name='estado_acuerdo'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'BORRADOR'::character varying"))

    with op.batch_alter_table('acuerdos_correctivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVO'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('compromiso', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('cumplido')
        batch_op.drop_column('compromisos')

    with op.batch_alter_table('acudientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_acudientes_colegio'), ['colegio_id'], unique=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.create_table('configuracion_evaluacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_captura', sa.VARCHAR(length=20), server_default=sa.text("'NUMERICA'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mostrar_boletin', sa.VARCHAR(length=20), server_default=sa.text("'AMBAS'::character varying"), autoincrement=False, nullable=False),
    sa.Column('nota_minima', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('nota_maxima', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('configuracion_evaluacion_colegio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('configuracion_evaluacion_pkey')),
    sa.UniqueConstraint('colegio_id', name=op.f('configuracion_evaluacion_colegio_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('modelo_evaluacion_estudiante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.CheckConstraint('porcentaje >= 0::numeric AND porcentaje <= 100::numeric', name=op.f('chk_porcentaje_modelo')),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('fk_modelo_eval_colegio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('modelo_evaluacion_estudiante_pkey')),
    sa.UniqueConstraint('colegio_id', 'nombre', name=op.f('unique_componente_colegio'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('colegio_id', 'orden', name=op.f('unique_orden_colegio'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ingresos_colegio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('hora', postgresql.TIME(), server_default=sa.text('CURRENT_TIME'), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=20), server_default=sa.text("'QR'::character varying"), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('tipo_evento', postgresql.ENUM('ingreso', 'salida', name='tipo_evento_colegio'), server_default=sa.text("'ingreso'::tipo_evento_colegio"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('fk_ingreso_colegio'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name=op.f('fk_ingreso_estudiante'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingresos_colegio_pkey'))
    )
    with op.batch_alter_table('ingresos_colegio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unico_evento_por_dia'), ['estudiante_id', 'fecha', 'tipo_evento'], unique=True)

    op.create_table('examen_contenido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('examen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], name=op.f('examen_contenido_examen_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examen_contenido_pkey')),
    sa.UniqueConstraint('examen_id', 'version', name=op.f('examen_contenido_examen_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('competencias_periodo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('periodo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('materia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.CheckConstraint('porcentaje >= 0::numeric AND porcentaje <= 100::numeric', name=op.f('chk_porcentaje_competencia')),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('fk_competencia_periodo_colegio'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_competencia_periodo_materia'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], name=op.f('fk_competencia_periodo_periodo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('competencias_periodo_pkey'))
    )
    op.create_table('componentes_evaluacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('fk_componente_colegio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('componentes_evaluacion_pkey'))
    )
    # ### end Alembic commands ###
