"""estructura_completa_supabase

Revision ID: 48daffe3eec0
Revises: 36a3c839603b
Create Date: 2026-06-10 07:26:23.039806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48daffe3eec0'
down_revision = '36a3c839603b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_gestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tiene_contexto', sa.Boolean(), nullable=True),
    sa.Column('tiene_json', sa.Boolean(), nullable=True),
    sa.Column('requiere_grupo', sa.Boolean(), nullable=True),
    sa.Column('tiempo_por_defecto', sa.Integer(), nullable=True),
    sa.Column('disponible_individual', sa.Boolean(), nullable=True),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_disciplinaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dias_prescripcion', sa.Integer(), nullable=True),
    sa.Column('max_tipo2', sa.Integer(), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_escalamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_origen', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_destino', sa.String(length=20), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escala_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nota_minima', sa.Float(), nullable=False),
    sa.Column('nota_maxima', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('archivo_json', sa.String(length=200), nullable=True),
    sa.Column('contenido_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tipo_examen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_examen_id'], ['tipo_examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['sede_id', 'colegio_id'], ['sedes.id', 'sedes.colegio_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('tokens_activacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('acuerdos_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'CERRADO', name='estado_acuerdo'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docente_id', 'anio', name='unique_docente_anio')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('anio_lectivo', sa.Integer(), nullable=False),
    sa.Column('grado', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=False),
    sa.Column('director_docente_id', sa.Integer(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['director_docente_id'], ['docentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas_colegio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterios_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acuerdo_id', sa.Integer(), nullable=False),
    sa.Column('area_gestion_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['acuerdo_id'], ['acuerdos_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['area_gestion_id'], ['areas_gestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acuerdo_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('puntaje_final', sa.Float(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acuerdo_id'], ['acuerdos_evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acuerdo_id')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('acuerdo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acuerdo_id'], ['acuerdos_evaluacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribuciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios_evaluacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion_criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_final_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.CheckConstraint('calificacion >= 0 AND calificacion <= 5', name='check_calificacion_rango'),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_final_id'], ['evaluacion_final.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_final_id', 'criterio_id', name='unique_evaluacion_criterio')
    )
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios_evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajustes_razonables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piar_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('aplicado', sa.Boolean(), nullable=False),
    sa.Column('fecha_aplicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piar_id'], ['piar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('justificaciones_acudiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('novedad_id', sa.Integer(), nullable=False),
    sa.Column('acudiente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acudiente_id'], ['acudientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novedad_id'], ['novedades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novedad_id')
    )
    op.create_table('respuestas_examen_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado_examen_id', sa.Integer(), nullable=False),
    sa.Column('numero_pregunta', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta_seleccionada', sa.String(length=300), nullable=False),
    sa.Column('respuesta_correcta', sa.String(length=300), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.Column('tiempo_respuesta_seg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultado_examen_id'], ['resultados_examen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_novedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novedad_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novedad_id'], ['novedades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citacion_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('destinatario', sa.String(length=120), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('proveedor', sa.String(length=50), nullable=True),
    sa.Column('id_proveedor', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citacion_id'], ['citaciones_acudiente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens_activacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_tipo'), ['tipo'], unique=False)

    op.drop_table('ingresos_colegio')
    with op.batch_alter_table('acudientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('colegio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('acuerdos_correctivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compromisos', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('cumplido', sa.Boolean(), nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('compromiso')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activa', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('atendida')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('citaciones_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_notificacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.drop_column('tipo_origen')
        batch_op.drop_column('fecha')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('competencias_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje', sa.Float(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('competencias_materia_materia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('orden')
        batch_op.drop_column('peso_porcentual')

    with op.batch_alter_table('descargos_estudiante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['novedad_id'])

    with op.batch_alter_table('estudiante_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unica_relacion', ['estudiante_id', 'acudiente_id'])

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('acudiente_principal_id', sa.Integer(), nullable=False))
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('estudiantes_docente_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('estudiantes_institucion_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'acudientes', ['acudiente_principal_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'docentes', ['docente_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'grupos', ['grupo_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('institucion_id')

    with op.batch_alter_table('evaluaciones_estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=False))
        batch_op.alter_column('indicador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('periodo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_periodo_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_competencia_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_estudiante_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('evaluaciones_estudiante_clase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'periodos', ['periodo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'estudiantes', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('calificacion')
        batch_op.drop_column('clase_id')
        batch_op.drop_column('competencia_id')

    with op.batch_alter_table('indicadores_logro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('indicadores_logro_competencia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencias_materia', ['competencia_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('nivel_desempeno')
        batch_op.drop_column('orden')
        batch_op.drop_column('peso_porcentual')

    with op.batch_alter_table('piar', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('resultados_examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuestas_correctas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('respuestas_incorrectas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('porcentaje', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('literal', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('cuestionario_archivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'examenes', ['examen_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=postgresql.ENUM('superadmin', 'admin_colegio', 'docente', 'estudiantes', 'acudiente', name='rol_usuario'),
               nullable=False)
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('rol',
               existing_type=postgresql.ENUM('superadmin', 'admin_colegio', 'docente', 'estudiantes', 'acudiente', name='rol_usuario'),
               nullable=True)

    with op.batch_alter_table('resultados_examen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_finalizacion')
        batch_op.drop_column('cuestionario_archivo')
        batch_op.drop_column('literal')
        batch_op.drop_column('porcentaje')
        batch_op.drop_column('respuestas_incorrectas')
        batch_op.drop_column('respuestas_correctas')

    with op.batch_alter_table('piar', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('indicadores_logro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_porcentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nivel_desempeno', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('indicadores_logro_competencia_id_fkey'), 'competencias_materia', ['competencia_id'], ['id'])

    with op.batch_alter_table('evaluaciones_estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clase_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calificacion', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_clase_id_fkey'), 'clases', ['clase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_estudiante_id_fkey'), 'estudiantes', ['estudiante_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_competencia_id_fkey'), 'competencias_materia', ['competencia_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('evaluaciones_estudiante_periodo_id_fkey'), 'periodos', ['periodo_id'], ['id'])
        batch_op.alter_column('periodo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('indicador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('nota')

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estudiantes_institucion_id_fkey'), 'colegios', ['institucion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('estudiantes_docente_id_fkey'), 'docentes', ['docente_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('acudiente_principal_id')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')
        batch_op.drop_column('grupo_id')

    with op.batch_alter_table('estudiante_acudiente', schema=None) as batch_op:
        batch_op.drop_constraint('unica_relacion', type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('descargos_estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('competencias_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_porcentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('competencias_materia_materia_id_fkey'), 'materias', ['materia_id'], ['id'])
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('porcentaje')

    with op.batch_alter_table('citaciones_acudiente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_origen', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('fecha_notificacion')

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atendida', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('activa')

    with op.batch_alter_table('acuerdos_correctivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('compromiso', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('cumplido')
        batch_op.drop_column('compromisos')

    with op.batch_alter_table('acudientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('colegio_id')
        batch_op.drop_column('direccion')

    op.create_table('ingresos_colegio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tipo_evento', postgresql.ENUM('INGRESO', 'SALIDA', name='tipoevento'), autoincrement=False, nullable=True),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('colegio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], name=op.f('ingresos_colegio_colegio_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name=op.f('ingresos_colegio_estudiante_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingresos_colegio_pkey'))
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_tipo'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_estado'))

    op.drop_table('notification_logs')
    op.drop_table('respuestas_novedad')
    op.drop_table('respuestas_examen_detalle')
    op.drop_table('justificaciones_acudiente')
    op.drop_table('ajustes_razonables')
    op.drop_table('evidencias')
    op.drop_table('evaluacion_criterio')
    op.drop_table('contribuciones')
    op.drop_table('seguimientos')
    op.drop_table('evaluacion_final')
    op.drop_table('criterios_evaluacion')
    op.drop_table('grupos')
    op.drop_table('acuerdos_evaluacion')
    op.drop_table('tokens_activacion')
    op.drop_table('coordinadores')
    op.drop_table('suscripciones')
    op.drop_table('periodos_academicos')
    op.drop_table('examenes')
    op.drop_table('escala_evaluacion')
    op.drop_table('configuracion_escalamiento')
    op.drop_table('configuracion_disciplinaria')
    op.drop_table('competencias')
    op.drop_table('tipo_examen')
    op.drop_table('areas_gestion')
    # ### end Alembic commands ###
