"""Corregir nombre nullable y campos de control de acceso

Revision ID: 4b601668fe68
Revises: 
Create Date: 2026-02-09 17:33:35.748725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b601668fe68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_aprobacion')
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('colegios_nombre_key'), type_='unique')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('docentes_colegio_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('permisos_colegio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('permisos_docente_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('permisos_aprobado_por_fkey'), type_='foreignkey')
        batch_op.drop_column('aprobado_por')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('colegio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fecha_expiracion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("(now() + '15 days'::interval)"))
        batch_op.drop_constraint(batch_op.f('usuarios_colegio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'])
        batch_op.drop_column('aprobado_permanentemente')
        batch_op.drop_column('estatus')
        batch_op.drop_column('acceso_definitivo')
        batch_op.drop_column('fecha_limite_prueba')
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.VARCHAR(length=20), server_default=sa.text("'colegio'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_limite_prueba', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acceso_definitivo', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estatus', sa.VARCHAR(length=20), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aprobado_permanentemente', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuarios_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('fecha_expiracion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("(now() + '15 days'::interval)"))
        batch_op.alter_column('colegio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprobado_por', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('permisos_aprobado_por_fkey'), 'usuarios', ['aprobado_por'], ['id'])
        batch_op.create_foreign_key(batch_op.f('permisos_docente_id_fkey'), 'docentes', ['docente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('permisos_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('docentes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('docentes_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('colegios_nombre_key'), ['nombre'], postgresql_nulls_not_distinct=False)

    op.create_table('solicitudes_aprobacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_limite', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_aprobacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('solicitudes_aprobacion_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('solicitudes_aprobacion_pkey'))
    )
    # ### end Alembic commands ###
